log:
  level: 10
  handlers:
    file: true
    stream: true
db:
  url:
    drivername: mysql+aiomysql
    username: asdf
    password: qwer
    host: localhost
    port: 3306
    database: mydb
  engine:
    echo: false
    pool_pre_ping: true
    pool_recycle: 3600